-- Captar Suite - Compatibilidade Legado (PostgreSQL)
-- Arquivo incremental: vamos adicionando tabelas conforme o legado.

BEGIN;

CREATE SCHEMA IF NOT EXISTS contrato;

-- ==========================================================
-- Tabela: contrato.contrato (equivalente ao legado SQL Server)
-- Origem: [contrato].[contrato]
-- ==========================================================

CREATE TABLE IF NOT EXISTS contrato.contrato (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on timestamp without time zone NULL,
  updated_on timestamp without time zone NULL,
  ano smallint NOT NULL,
  numero varchar(20) NULL,
  descricao varchar(80) NULL,
  licitacao varchar(20) NULL,
  dispensa varchar(20) NULL,
  dt_assinatura date NULL,
  dt_publicacao date NULL,
  dt_inicio date NULL,
  dt_vencimento date NULL,
  responsavel_juridico varchar(100) NULL,
  vl_mao_obra numeric(29,6) NULL DEFAULT 0,
  vl numeric(29,6) NOT NULL DEFAULT 0,
  objeto text NULL,
  execucao text NULL,
  status varchar(32) NULL,
  testemunha varchar(100) NULL,
  testemunha2 varchar(100) NULL,
  cpf_testemunha varchar(14) NULL,
  cpf_testemunha2 varchar(14) NULL,
  contrato_anterior_id bigint NULL,
  created_by_id bigint NULL,
  empresa_id bigint NULL,
  fornecedor_id bigint NULL,
  tipo_contrato_id bigint NULL,
  updated_by_id bigint NULL,
  vl_unitario numeric(29,6) NULL DEFAULT 0,
  qt numeric(29,6) NULL DEFAULT 0,
  vl_total numeric(29,6) NULL DEFAULT 0,
  tp_contrato varchar(32) NULL,
  prazo_entrega date NULL,
  observacao text NULL,
  vl_comissao numeric(29,6) NULL DEFAULT 0,
  deposito_id bigint NULL,
  insumo_id bigint NULL,
  fazenda_id bigint NULL,
  fazenda_origem varchar(200) NULL,
  comissionado_id bigint NULL,
  tabela_preco_id bigint NULL,
  fazenda_destino_id bigint NULL,
  tp_entrada varchar(32) NULL,
  frete_confinamento varchar(32) NULL,
  sexo varchar(32) NULL,
  emissor_nota varchar(32) NULL,
  jejum varchar(32) NULL,
  qt_animal int NULL,
  qt_animal_mapa int NULL,
  vl_cepea numeric(29,6) NULL DEFAULT 0,
  vl_arroba numeric(29,6) NULL DEFAULT 0,
  vl_cabeca numeric(29,6) NULL DEFAULT 0,
  peso_bruto_total numeric(29,6) NULL DEFAULT 0,
  peso_bruto_cabeca numeric(29,6) NULL DEFAULT 0,
  peso_rc numeric(29,6) NULL DEFAULT 0,
  peso_medio_arroba numeric(29,6) NULL DEFAULT 0,
  previsao_chegada date NULL,
  vl_total_compra numeric(29,6) NULL DEFAULT 0,
  peso_medio_abate numeric(29,6) NULL DEFAULT 0,
  gmd_projetado numeric(29,6) NULL DEFAULT 0,
  gmc_projetado numeric(29,6) NULL DEFAULT 0,
  consumo_pv numeric(29,6) NULL DEFAULT 0,
  custo_ton_ms numeric(29,6) NULL DEFAULT 0,
  custo_ton_ms_vendido numeric(29,6) NULL DEFAULT 0,
  custo_operacional numeric(29,6) NULL DEFAULT 0,
  custo_operacional_vendido numeric(29,6) NULL DEFAULT 0,
  vl_frete_cab numeric(29,6) NULL DEFAULT 0,
  vl_icms numeric(29,6) NULL DEFAULT 0,
  vl_icms_frete numeric(29,6) NULL DEFAULT 0,
  vl_protocolo numeric(29,6) NULL DEFAULT 0,
  vl_brinco numeric(29,6) NULL DEFAULT 0,
  vl_gta_cab numeric(29,6) NULL DEFAULT 0,
  dias_minimos int NULL,
  dls date NULL,
  hr_pesagem time NULL,
  vl_frete_arroba numeric(29,6) NULL DEFAULT 0,
  vendedor_id bigint NULL,
  comprador_id bigint NULL,
  faturador_id bigint NULL,
  frigorifico_id bigint NULL,
  rc_fixo numeric(29,6) NULL DEFAULT 0,
  dt_embarque date NULL,
  dt_pesagem date NULL,
  dt_abate date NULL,
  dt_recebimento date NULL,
  observacao_financeiro text NULL,
  tp_saida varchar(32) NULL,
  originador_id bigint NULL,
  tabela_boitel_id bigint NULL,
  periodo_producao_id bigint NULL,
  permuta boolean NULL DEFAULT false,
  contrato_permuta_id bigint NULL,
  contrato_cedente_id bigint NULL,
  aditivo boolean NULL DEFAULT false,
  tp_aditivo_id bigint NULL,
  parceiro_id bigint NULL,
  dt_fim date NULL,
  responsavel_juridico_id bigint NULL,
  tp_contrato_id bigint NULL,
  pedido_id bigint NULL,
  peso_referencia varchar(32) NULL,
  qt_animal_gta int NULL,
  qt_animal_desembarcado int NULL,
  qt_animal_morto int NULL,
  qt_animal_lesionado int NULL,
  peso_total_quebra numeric(29,6) NULL DEFAULT 0,
  tp varchar(4000) NULL,
  rc_entrada numeric(29,6) NULL DEFAULT 0,
  peso_medio_mapa numeric(29,6) NULL DEFAULT 0,
  peso_medio_chegada decimal(28,8) NOT NULL DEFAULT 0,
  dt_pesagem_origem date NULL,
  dt_previsao_chegada date NULL,
  rc_saida numeric(29,6) NULL DEFAULT 0,
  vl_arroba_saida numeric(29,6) NULL DEFAULT 0,
  calculo_frete varchar(4000) NULL,
  frete varchar(4000) NULL,
  vl_unit_frete numeric(29,6) NULL DEFAULT 0,
  vl_arroba_produzida numeric(29,6) NULL DEFAULT 0,
  desconto_acerto boolean NULL DEFAULT false,
  valor_venda_futura boolean NULL,
  faturador_entrada_id bigint NULL,
  descricao_desconto varchar(4000) NULL,
  tx_juros_parceiro numeric(29,6) NULL DEFAULT 0,
  qt_animal_previsto decimal(29,6) NULL DEFAULT 0,
  qt_animal_selecionado decimal(29,6) NULL DEFAULT 0,
  current_approval_level_id bigint NULL,
  rota_id bigint NULL,
  old__distancia numeric(29,6) NULL DEFAULT 0,
  comissao_id bigint NULL,
  old__distancia_1 int NULL,
  distancia decimal(29,6) NULL DEFAULT 0,
  condicao_pagamento_id bigint NULL,
  ref_model varchar(128) NULL,
  ref_object_id bigint NULL,
  categoria_id bigint NULL,
  venda_futura boolean NULL DEFAULT false,
  cidade_id bigint NULL,
  estado_id bigint NULL,
  contato varchar(200) NULL,
  clausula_id bigint NULL,
  titulo_clausula varchar(100) NULL,
  assinatura_empresa varchar(100) NULL,
  assinatura_parceiro varchar(100) NULL,
  forma_pagamento_id bigint NULL,
  qt_animal_chegada int NULL,
  responsavel_quebra varchar(32) NULL,
  peso_medio_identificacao numeric(28,10) NULL DEFAULT 0,
  qt_animal_processamento numeric(28,10) NULL DEFAULT 0,
  programacao_retirada text NULL,
  programacao_pagamento text NULL,
  vl_arroba_dif numeric(28,10) NULL DEFAULT 0,
  vl_oferta decimal(28,8) NULL DEFAULT 0,
  vl_contra_oferta decimal(28,8) NULL DEFAULT 0,
  vl_tabela decimal(28,8) NULL DEFAULT 0,
  quebra_peso_kg decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_arr decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_pct decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_curral_kg decimal(28,8) NULL DEFAULT 0,
  quebra_peso_curral_arr decimal(28,8) NULL DEFAULT 0,
  quebra_peso_curral_pct decimal(28,8) NULL DEFAULT 0,
  qt_animal_trava int NULL,
  vl_arroba_trava decimal(28,8) NULL DEFAULT 0,
  contrato_principal_id bigint NULL,
  contraoferta varchar(1) NULL,
  calculo_adiantamento varchar(32) NULL,
  vl_desconto_adiantamento decimal(28,8) NULL DEFAULT 0,
  fazenda_origem_fk_id bigint NULL,
  pct_parceria decimal(28,6) NULL DEFAULT 0,
  pct_recria decimal(28,6) NULL DEFAULT 0,
  vl_desconto_venda decimal(28,6) NULL DEFAULT 0,
  referencia_diaria varchar(32) NULL,
  vl_diaria decimal(28,6) NULL,
  peso_considerado decimal(28,6) NULL,
  raca_id bigint NULL,
  tabela_produzida_id bigint NULL,
  _vl_comissao numeric(28,10) NULL,
  b1_codigo_pedido varchar(128) NULL,
  b1_codigo varchar(128) NULL,
  b1_created_by varchar(128) NULL,
  b1_approved_by varchar(128) NULL,
  b1_object_name varchar(128) NULL,
  b1_vl_pago decimal(28,6) NULL
);

CREATE INDEX IF NOT EXISTS idx_contrato_contrato_tp ON contrato.contrato (tp_contrato);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_ano_numero ON contrato.contrato (ano, numero);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_parceiro ON contrato.contrato (parceiro_id);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_empresa ON contrato.contrato (empresa_id);

-- Trigger de updated_on (usa a função contrato.set_updated_on)
DROP TRIGGER IF EXISTS trg_contrato_set_updated_on ON contrato.contrato;
CREATE TRIGGER trg_contrato_set_updated_on
BEFORE UPDATE ON contrato.contrato
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

-- FKs condicionais (só cria se tabela de referência existir)
DO $$
BEGIN
  IF to_regclass('contrato.clausula') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_clausula_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_clausula_id
      FOREIGN KEY (clausula_id) REFERENCES contrato.clausula(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_origem_fk_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_origem_fk_id
      FOREIGN KEY (fazenda_origem_fk_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('produto.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_forma_pagamento_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_forma_pagamento_id
      FOREIGN KEY (forma_pagamento_id) REFERENCES produto.condicao_pagamento(id);
  END IF;

  IF to_regclass('confinamento.raca') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_raca_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_raca_id
      FOREIGN KEY (raca_id) REFERENCES confinamento.raca(id);
  END IF;

  IF to_regclass('confinamento.tabela_produzida') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_produzida_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_produzida_id
      FOREIGN KEY (tabela_produzida_id) REFERENCES confinamento.tabela_produzida(id);
  END IF;

  IF to_regclass('confinamento.categoria') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_categoria_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_categoria_id
      FOREIGN KEY (categoria_id) REFERENCES confinamento.categoria(id);
  END IF;

  IF to_regclass('dbo.res_city') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_cidade_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_cidade_id
      FOREIGN KEY (cidade_id) REFERENCES dbo.res_city(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comissao_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comissao_id
      FOREIGN KEY (comissao_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comissionado_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comissionado_id
      FOREIGN KEY (comissionado_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comprador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comprador_id
      FOREIGN KEY (comprador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('confinamento.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_condicao_pagamento_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_condicao_pagamento_id
      FOREIGN KEY (condicao_pagamento_id) REFERENCES confinamento.condicao_pagamento(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_anterior_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_anterior_id
      FOREIGN KEY (contrato_anterior_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_cedente_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_cedente_id
      FOREIGN KEY (contrato_cedente_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_permuta_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_permuta_id
      FOREIGN KEY (contrato_permuta_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_created_by_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.mail_approval_level') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_current_approval_level_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_current_approval_level_id
      FOREIGN KEY (current_approval_level_id) REFERENCES dbo.mail_approval_level(id);
  END IF;

  IF to_regclass('estoque.deposito') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_deposito_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_deposito_id
      FOREIGN KEY (deposito_id) REFERENCES estoque.deposito(id);
  END IF;

  IF to_regclass('dbo.res_company') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_empresa_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_empresa_id
      FOREIGN KEY (empresa_id) REFERENCES dbo.res_company(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_country_state') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_estado_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_estado_id
      FOREIGN KEY (estado_id) REFERENCES dbo.res_country_state(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_faturador_entrada_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_faturador_entrada_id
      FOREIGN KEY (faturador_entrada_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_faturador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_faturador_id
      FOREIGN KEY (faturador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_destino_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_destino_id
      FOREIGN KEY (fazenda_destino_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_id
      FOREIGN KEY (fazenda_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fornecedor_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fornecedor_id
      FOREIGN KEY (fornecedor_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_frigorifico_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_frigorifico_id
      FOREIGN KEY (frigorifico_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('produto.item') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_insumo_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_insumo_id
      FOREIGN KEY (insumo_id) REFERENCES produto.item(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_originador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_originador_id
      FOREIGN KEY (originador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_parceiro_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_parceiro_id
      FOREIGN KEY (parceiro_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('produto.pedido') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_pedido_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_pedido_id
      FOREIGN KEY (pedido_id) REFERENCES produto.pedido(id);
  END IF;

  IF to_regclass('agricola.periodo_producao') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_periodo_producao_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_periodo_producao_id
      FOREIGN KEY (periodo_producao_id) REFERENCES agricola.periodo_producao(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_responsavel_juridico_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_responsavel_juridico_id
      FOREIGN KEY (responsavel_juridico_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_rota_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_rota_id
      FOREIGN KEY (rota_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('confinamento.tabela_boitel') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_boitel_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_boitel_id
      FOREIGN KEY (tabela_boitel_id) REFERENCES confinamento.tabela_boitel(id);
  END IF;

  IF to_regclass('confinamento.tabela_preco') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_preco_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_preco_id
      FOREIGN KEY (tabela_preco_id) REFERENCES confinamento.tabela_preco(id);
  END IF;

  IF to_regclass('contrato.tipo_contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tipo_contrato_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tipo_contrato_id
      FOREIGN KEY (tipo_contrato_id) REFERENCES contrato.tipo_contrato(id);
  END IF;

  IF to_regclass('contrato.tipo_aditivo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tp_aditivo_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tp_aditivo_id
      FOREIGN KEY (tp_aditivo_id) REFERENCES contrato.tipo_aditivo(id);
  END IF;

  IF to_regclass('contrato.tipo_contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tp_contrato_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tp_contrato_id
      FOREIGN KEY (tp_contrato_id) REFERENCES contrato.tipo_contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_updated_by_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_vendedor_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_vendedor_id
      FOREIGN KEY (vendedor_id) REFERENCES dbo.res_partner(id);
  END IF;
END $$;

-- ==========================================================
-- Tabela: contrato.contrato_item (equivalente ao legado SQL Server)
-- Origem: [contrato].[contrato_item]
-- ==========================================================

CREATE TABLE IF NOT EXISTS contrato.contrato_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  created_by_id bigint NULL,
  contrato_id bigint NOT NULL,
  item_id bigint NULL,
  vl_unitario numeric(29,6) NULL DEFAULT 0,
  qt numeric(29,6) NULL DEFAULT 0,
  vl_total numeric(29,6) NULL DEFAULT 0,
  vl_comissao numeric(29,6) NULL DEFAULT 0,
  prazo_entrega date NULL,
  condicao_pagamento_id bigint NULL,
  deposito_id bigint NULL,
  udm_id bigint NULL,
  cc1_id bigint NULL,
  cc2_id bigint NULL,
  cc3_id bigint NULL,
  cc4_id bigint NULL,
  cc5_id bigint NULL,
  qt_saldo decimal(29,6) NULL DEFAULT 0,
  cc_id bigint NULL,
  utilizacao_id bigint NULL,
  moeda_id bigint NULL,
  item_codigo_snapshot varchar(64) NULL,
  item_nome_snapshot varchar(255) NULL,
  item_label_snapshot varchar(255) NULL,
  udm_label_snapshot varchar(120) NULL,
  condicao_pagamento_label_snapshot varchar(255) NULL,
  deposito_label_snapshot varchar(255) NULL,
  centro_custo_label_snapshot varchar(255) NULL,
  utilizacao_label_snapshot varchar(255) NULL,
  moeda_label_snapshot varchar(120) NULL
);  

ALTER TABLE contrato.contrato_item
  ADD COLUMN IF NOT EXISTS item_codigo_snapshot varchar(64),
  ADD COLUMN IF NOT EXISTS item_nome_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS item_label_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS udm_label_snapshot varchar(120),
  ADD COLUMN IF NOT EXISTS condicao_pagamento_label_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS deposito_label_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS centro_custo_label_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS utilizacao_label_snapshot varchar(255),
  ADD COLUMN IF NOT EXISTS moeda_label_snapshot varchar(120);

CREATE INDEX IF NOT EXISTS idx_contrato_item_contrato_id ON contrato.contrato_item (contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_item_item_id ON contrato.contrato_item (item_id);
CREATE INDEX IF NOT EXISTS idx_contrato_item_condicao_pagamento_id ON contrato.contrato_item (condicao_pagamento_id);
CREATE INDEX IF NOT EXISTS idx_contrato_item_deposito_id ON contrato.contrato_item (deposito_id);

-- Trigger de updated_on
CREATE OR REPLACE FUNCTION contrato.set_updated_on()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_on = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contrato_item_set_updated_on ON contrato.contrato_item;
CREATE TRIGGER trg_contrato_item_set_updated_on
BEFORE UPDATE ON contrato.contrato_item
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

-- FKs condicionais (só cria se tabela de referência existir)
DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_contrato_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc_id
      FOREIGN KEY (cc_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc1_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc1_id
      FOREIGN KEY (cc1_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc2_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc2_id
      FOREIGN KEY (cc2_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc3_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc3_id
      FOREIGN KEY (cc3_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc4_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc4_id
      FOREIGN KEY (cc4_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('br.centro_custo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_cc5_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_cc5_id
      FOREIGN KEY (cc5_id) REFERENCES br.centro_custo(id);
  END IF;

  IF to_regclass('dbo.res_currency') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_moeda_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_moeda_id
      FOREIGN KEY (moeda_id) REFERENCES dbo.res_currency(id);
  END IF;

  IF to_regclass('produto.utilizacao') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_utilizacao_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_utilizacao_id
      FOREIGN KEY (utilizacao_id) REFERENCES produto.utilizacao(id);
  END IF;

  IF to_regclass('produto.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_condicao_pagamento_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_condicao_pagamento_id
      FOREIGN KEY (condicao_pagamento_id) REFERENCES produto.condicao_pagamento(id);
  END IF;

  IF to_regclass('estoque.deposito') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_deposito_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_deposito_id
      FOREIGN KEY (deposito_id) REFERENCES estoque.deposito(id);
  END IF;

  IF to_regclass('produto.item') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_item_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_item_id
      FOREIGN KEY (item_id) REFERENCES produto.item(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_created_by_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_updated_by_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('produto.unidade') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_item_udm_id') THEN
    ALTER TABLE contrato.contrato_item
      ADD CONSTRAINT fk_contrato_item_udm_id
      FOREIGN KEY (udm_id) REFERENCES produto.unidade(id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.unidade_medida (equivalente ao legado SQL Server)
-- Origem: [contrato].[unidade_medida]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.unidade_medida (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  sigla varchar(10) NULL,
  descricao varchar(50) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_unidade_medida_sigla ON contrato.unidade_medida (sigla);
CREATE INDEX IF NOT EXISTS idx_unidade_medida_descricao ON contrato.unidade_medida (descricao);

DROP TRIGGER IF EXISTS trg_unidade_medida_set_updated_on ON contrato.unidade_medida;
CREATE TRIGGER trg_unidade_medida_set_updated_on
BEFORE UPDATE ON contrato.unidade_medida
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_medida_created_by_id') THEN
    ALTER TABLE contrato.unidade_medida
      ADD CONSTRAINT fk_unidade_medida_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_medida_updated_by_id') THEN
    ALTER TABLE contrato.unidade_medida
      ADD CONSTRAINT fk_unidade_medida_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.certidao (equivalente ao legado SQL Server)
-- Origem: [contrato].[certidao]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.certidao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(50) NULL,
  dt_emissao date NULL,
  dt_validade date NULL,
  dt_competencia date NULL,
  contrato_id bigint NOT NULL,
  created_by_id bigint NULL,
  tipo_certidao_id bigint NOT NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_certidao_contrato_id ON contrato.certidao (contrato_id);
CREATE INDEX IF NOT EXISTS idx_certidao_tipo_certidao_id ON contrato.certidao (tipo_certidao_id);

DROP TRIGGER IF EXISTS trg_certidao_set_updated_on ON contrato.certidao;
CREATE TRIGGER trg_certidao_set_updated_on
BEFORE UPDATE ON contrato.certidao
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_certidao_contrato_id') THEN
    ALTER TABLE contrato.certidao
      ADD CONSTRAINT fk_certidao_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_certidao_created_by_id') THEN
    ALTER TABLE contrato.certidao
      ADD CONSTRAINT fk_certidao_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('contrato.tipo_certidao') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_certidao_tipo_certidao_id') THEN
    ALTER TABLE contrato.certidao
      ADD CONSTRAINT fk_certidao_tipo_certidao_id
      FOREIGN KEY (tipo_certidao_id) REFERENCES contrato.tipo_certidao(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_certidao_updated_by_id') THEN
    ALTER TABLE contrato.certidao
      ADD CONSTRAINT fk_certidao_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;


-- ==========================================================
-- Tabela: contrato.clausula (equivalente ao legado SQL Server)
-- Origem: [contrato].[clausula]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.clausula (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar(100) NOT NULL,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL,
  codigo varchar(100) NULL,
  _descricao varchar(1024) NULL,
  CONSTRAINT uq_clausula_descricao UNIQUE (descricao)
);

CREATE INDEX IF NOT EXISTS idx_clausula_codigo ON contrato.clausula (codigo);

DROP TRIGGER IF EXISTS trg_clausula_set_updated_on ON contrato.clausula;
CREATE TRIGGER trg_clausula_set_updated_on
BEFORE UPDATE ON contrato.clausula
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_created_by_id') THEN
    ALTER TABLE contrato.clausula
      ADD CONSTRAINT fk_clausula_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_updated_by_id') THEN
    ALTER TABLE contrato.clausula
      ADD CONSTRAINT fk_clausula_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.clausula_contrato (equivalente ao legado SQL Server)
-- Origem: [contrato].[clausula_contrato]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.clausula_contrato (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NULL,
  codigo varchar(50) NULL,
  referencia varchar(100) NULL,
  descricao text NULL,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS idx_clausula_contrato_contrato_id ON contrato.clausula_contrato (contrato_id);
CREATE INDEX IF NOT EXISTS idx_clausula_contrato_codigo ON contrato.clausula_contrato (codigo);

DROP TRIGGER IF EXISTS trg_clausula_contrato_set_updated_on ON contrato.clausula_contrato;
CREATE TRIGGER trg_clausula_contrato_set_updated_on
BEFORE UPDATE ON contrato.clausula_contrato
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_contrato_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_created_by_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_updated_by_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.clausula_item (equivalente ao legado SQL Server)
-- Origem: [contrato].[clausula_item]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.clausula_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clausula_id bigint NULL,
  codigo varchar(50) NULL,
  referencia varchar(100) NULL,
  descricao text NULL,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS idx_clausula_item_clausula_id ON contrato.clausula_item (clausula_id);
CREATE INDEX IF NOT EXISTS idx_clausula_item_codigo ON contrato.clausula_item (codigo);

DROP TRIGGER IF EXISTS trg_clausula_item_set_updated_on ON contrato.clausula_item;
CREATE TRIGGER trg_clausula_item_set_updated_on
BEFORE UPDATE ON contrato.clausula_item
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.clausula') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_item_clausula_id') THEN
    ALTER TABLE contrato.clausula_item
      ADD CONSTRAINT fk_clausula_item_clausula_id
      FOREIGN KEY (clausula_id) REFERENCES contrato.clausula(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_item_created_by_id') THEN
    ALTER TABLE contrato.clausula_item
      ADD CONSTRAINT fk_clausula_item_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_item_updated_by_id') THEN
    ALTER TABLE contrato.clausula_item
      ADD CONSTRAINT fk_clausula_item_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.contrato_nf (equivalente ao legado SQL Server)
-- Origem: [contrato].[contrato_nf]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.contrato_nf (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NOT NULL,
  nf_id bigint NOT NULL,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS idx_contrato_nf_contrato_id ON contrato.contrato_nf (contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_nf_nf_id ON contrato.contrato_nf (nf_id);

DROP TRIGGER IF EXISTS trg_contrato_nf_set_updated_on ON contrato.contrato_nf;
CREATE TRIGGER trg_contrato_nf_set_updated_on
BEFORE UPDATE ON contrato.contrato_nf
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_nf_contrato_id') THEN
    ALTER TABLE contrato.contrato_nf
      ADD CONSTRAINT fk_contrato_nf_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_nf_created_by_id') THEN
    ALTER TABLE contrato.contrato_nf
      ADD CONSTRAINT fk_contrato_nf_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('produto.nf') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_nf_nf_id') THEN
    ALTER TABLE contrato.contrato_nf
      ADD CONSTRAINT fk_contrato_nf_nf_id
      FOREIGN KEY (nf_id) REFERENCES produto.nf(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_nf_updated_by_id') THEN
    ALTER TABLE contrato.contrato_nf
      ADD CONSTRAINT fk_contrato_nf_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.contrato_previsao (equivalente ao legado SQL Server)
-- Origem: [contrato].[contrato_previsao]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.contrato_previsao (
  contrato_id bigint NULL,
  dt_inicio date NULL,
  qt decimal(28,6) NOT NULL DEFAULT 0,
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS idx_contrato_previsao_contrato_id ON contrato.contrato_previsao (contrato_id);
CREATE INDEX IF NOT EXISTS idx_contrato_previsao_dt_inicio ON contrato.contrato_previsao (dt_inicio);

DROP TRIGGER IF EXISTS trg_contrato_previsao_set_updated_on ON contrato.contrato_previsao;
CREATE TRIGGER trg_contrato_previsao_set_updated_on
BEFORE UPDATE ON contrato.contrato_previsao
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_previsao_contrato_id') THEN
    ALTER TABLE contrato.contrato_previsao
      ADD CONSTRAINT fk_contrato_previsao_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.convenio (equivalente ao legado SQL Server)
-- Origem: [contrato].[convenio]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.convenio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  ano smallint NOT NULL,
  numero integer NOT NULL,
  original varchar(20) NULL,
  descricao varchar(100) NULL,
  objeto text NULL,
  vl_concedente numeric(29,6) NULL DEFAULT 0,
  vl_executor numeric(29,6) NULL DEFAULT 0,
  vl_total numeric(29,6) NULL DEFAULT 0,
  titulo varchar(30) NULL,
  dt_assinatura date NULL,
  dt_inicio date NULL,
  dt_fim date NULL,
  dt_publicacao date NULL,
  parecer_juridico varchar(100) NULL,
  dt_parecer date NULL,
  responsavel_juridico varchar(100) NULL,
  lei_autorizativa varchar(20) NULL,
  dt_lei date NULL,
  vl_parcela numeric(29,6) NULL DEFAULT 0,
  agencia_banco varchar(30) NULL,
  conta_banco varchar(20) NULL,
  obs text NULL,
  banco_id bigint NULL,
  created_by_id bigint NULL,
  empresa_id bigint NULL,
  fornecedor_id bigint NULL,
  moeda_id bigint NULL,
  orgao_superior_id bigint NULL,
  parent_id bigint NULL,
  periodo_pagamento_id bigint NULL,
  tp_aditivo_id bigint NULL,
  tp_convenio_id bigint NULL,
  updated_by_id bigint NULL,
  parceiro_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_convenio_ano_numero ON contrato.convenio (ano, numero);
CREATE INDEX IF NOT EXISTS idx_convenio_empresa_id ON contrato.convenio (empresa_id);
CREATE INDEX IF NOT EXISTS idx_convenio_parceiro_id ON contrato.convenio (parceiro_id);

DROP TRIGGER IF EXISTS trg_convenio_set_updated_on ON contrato.convenio;
CREATE TRIGGER trg_convenio_set_updated_on
BEFORE UPDATE ON contrato.convenio
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_parceiro_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_parceiro_id
      FOREIGN KEY (parceiro_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('br.banco') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_banco_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_banco_id
      FOREIGN KEY (banco_id) REFERENCES br.banco(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_created_by_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_company') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_empresa_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_empresa_id
      FOREIGN KEY (empresa_id) REFERENCES dbo.res_company(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_fornecedor_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_fornecedor_id
      FOREIGN KEY (fornecedor_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_currency') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_moeda_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_moeda_id
      FOREIGN KEY (moeda_id) REFERENCES dbo.res_currency(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_orgao_superior_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_orgao_superior_id
      FOREIGN KEY (orgao_superior_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('contrato.convenio') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_parent_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_parent_id
      FOREIGN KEY (parent_id) REFERENCES contrato.convenio(id);
  END IF;

  IF to_regclass('contrato.periodo_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_periodo_pagamento_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_periodo_pagamento_id
      FOREIGN KEY (periodo_pagamento_id) REFERENCES contrato.periodo_pagamento(id);
  END IF;

  IF to_regclass('contrato.tipo_aditivo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_tp_aditivo_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_tp_aditivo_id
      FOREIGN KEY (tp_aditivo_id) REFERENCES contrato.tipo_aditivo(id);
  END IF;

  IF to_regclass('contrato.tipo_convenio') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_tp_convenio_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_tp_convenio_id
      FOREIGN KEY (tp_convenio_id) REFERENCES contrato.tipo_convenio(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_updated_by_id') THEN
    ALTER TABLE contrato.convenio
      ADD CONSTRAINT fk_convenio_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.convenio_participante (equivalente ao legado SQL Server)
-- Origem: [contrato].[convenio_participante]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.convenio_participante (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  funcao varchar(50) NULL,
  vl numeric(29,6) NULL DEFAULT 0,
  dt_inicio date NULL,
  dt_fim date NULL,
  convenio_id bigint NOT NULL,
  created_by_id bigint NULL,
  fornecedor_id bigint NOT NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_convenio_participante_convenio_id ON contrato.convenio_participante (convenio_id);
CREATE INDEX IF NOT EXISTS idx_convenio_participante_fornecedor_id ON contrato.convenio_participante (fornecedor_id);

DROP TRIGGER IF EXISTS trg_convenio_participante_set_updated_on ON contrato.convenio_participante;
CREATE TRIGGER trg_convenio_participante_set_updated_on
BEFORE UPDATE ON contrato.convenio_participante
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.convenio') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_participante_convenio_id') THEN
    ALTER TABLE contrato.convenio_participante
      ADD CONSTRAINT fk_convenio_participante_convenio_id
      FOREIGN KEY (convenio_id) REFERENCES contrato.convenio(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_participante_created_by_id') THEN
    ALTER TABLE contrato.convenio_participante
      ADD CONSTRAINT fk_convenio_participante_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_participante_fornecedor_id') THEN
    ALTER TABLE contrato.convenio_participante
      ADD CONSTRAINT fk_convenio_participante_fornecedor_id
      FOREIGN KEY (fornecedor_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_convenio_participante_updated_by_id') THEN
    ALTER TABLE contrato.convenio_participante
      ADD CONSTRAINT fk_convenio_participante_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.financeiro (equivalente ao legado SQL Server)
-- Origem: [contrato].[financeiro]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.financeiro (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NULL,
  tp varchar(4000) NULL,
  dt date NULL,
  vl numeric(29,6) NULL DEFAULT 0,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL,
  descricao varchar(4000) NULL,
  tx numeric(29,6) NULL DEFAULT 0,
  dias_referencia integer NULL,
  forma_pagamento_id bigint NULL,
  condicao_pagamento_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_financeiro_contrato_id ON contrato.financeiro (contrato_id);
CREATE INDEX IF NOT EXISTS idx_financeiro_dt ON contrato.financeiro (dt);

DROP TRIGGER IF EXISTS trg_financeiro_set_updated_on ON contrato.financeiro;
CREATE TRIGGER trg_financeiro_set_updated_on
BEFORE UPDATE ON contrato.financeiro
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('produto.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_financeiro_condicao_pagamento_id') THEN
    ALTER TABLE contrato.financeiro
      ADD CONSTRAINT fk_financeiro_condicao_pagamento_id
      FOREIGN KEY (condicao_pagamento_id) REFERENCES produto.condicao_pagamento(id);
  END IF;

  IF to_regclass('produto.forma_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_financeiro_forma_pagamento_id') THEN
    ALTER TABLE contrato.financeiro
      ADD CONSTRAINT fk_financeiro_forma_pagamento_id
      FOREIGN KEY (forma_pagamento_id) REFERENCES produto.forma_pagamento(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_financeiro_contrato_id') THEN
    ALTER TABLE contrato.financeiro
      ADD CONSTRAINT fk_financeiro_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_financeiro_created_by_id') THEN
    ALTER TABLE contrato.financeiro
      ADD CONSTRAINT fk_financeiro_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_financeiro_updated_by_id') THEN
    ALTER TABLE contrato.financeiro
      ADD CONSTRAINT fk_financeiro_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.funcao_obra (equivalente ao legado SQL Server)
-- Origem: [contrato].[funcao_obra]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.funcao_obra (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  codigo varchar(10) NOT NULL,
  descricao varchar(100) NOT NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL,
  CONSTRAINT uq_funcao_obra_codigo UNIQUE (codigo),
  CONSTRAINT uq_funcao_obra_descricao UNIQUE (descricao)
);

DROP TRIGGER IF EXISTS trg_funcao_obra_set_updated_on ON contrato.funcao_obra;
CREATE TRIGGER trg_funcao_obra_set_updated_on
BEFORE UPDATE ON contrato.funcao_obra
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_funcao_obra_created_by_id') THEN
    ALTER TABLE contrato.funcao_obra
      ADD CONSTRAINT fk_funcao_obra_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_funcao_obra_updated_by_id') THEN
    ALTER TABLE contrato.funcao_obra
      ADD CONSTRAINT fk_funcao_obra_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.obra (equivalente ao legado SQL Server)
-- Origem: [contrato].[obra]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.obra (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on timestamp without time zone NULL,
  updated_on timestamp without time zone NULL,
  ano smallint NOT NULL,
  numero varchar(20) NULL,
  dt_cadastro date NOT NULL,
  descricao text NULL,
  prazo smallint NULL,
  dt_situacao date NULL,
  dt_recebimento date NULL,
  dt_inicio date NULL,
  dt_aceite date NULL,
  status varchar(32) NULL,
  justificativa text NULL,
  licitacao varchar(20) NULL,
  possui_contrato boolean NULL DEFAULT false,
  contrato_id bigint NULL,
  created_by_id bigint NULL,
  empresa_id bigint NULL,
  funcao_id bigint NULL,
  local_obra_id bigint NULL,
  tipo_id bigint NULL,
  unidade_medida_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_obra_ano_numero ON contrato.obra (ano, numero);
CREATE INDEX IF NOT EXISTS idx_obra_contrato_id ON contrato.obra (contrato_id);
CREATE INDEX IF NOT EXISTS idx_obra_empresa_id ON contrato.obra (empresa_id);

DROP TRIGGER IF EXISTS trg_obra_set_updated_on ON contrato.obra;
CREATE TRIGGER trg_obra_set_updated_on
BEFORE UPDATE ON contrato.obra
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_contrato_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_created_by_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_company') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_empresa_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_empresa_id
      FOREIGN KEY (empresa_id) REFERENCES dbo.res_company(partner_ptr_id);
  END IF;

  IF to_regclass('contrato.funcao_obra') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_funcao_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_funcao_id
      FOREIGN KEY (funcao_id) REFERENCES contrato.funcao_obra(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_local_obra_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_local_obra_id
      FOREIGN KEY (local_obra_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('contrato.tipo_obra') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_tipo_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_tipo_id
      FOREIGN KEY (tipo_id) REFERENCES contrato.tipo_obra(id);
  END IF;

  IF to_regclass('contrato.unidade_medida') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_unidade_medida_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_unidade_medida_id
      FOREIGN KEY (unidade_medida_id) REFERENCES contrato.unidade_medida(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_obra_updated_by_id') THEN
    ALTER TABLE contrato.obra
      ADD CONSTRAINT fk_obra_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.parametro (equivalente ao legado SQL Server)
-- Origem: [contrato].[parametro]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.parametro (
  modo varchar(32) NOT NULL,
  numeracao_automatica boolean NOT NULL DEFAULT true,
  configuracao varchar(32) NOT NULL,
  sequencia integer NULL,
  tamanho integer NULL,
  separador varchar(1) NULL,
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL,
  pedido_venda boolean NULL,
  pedido_compra boolean NULL
);

CREATE INDEX IF NOT EXISTS idx_parametro_modo_configuracao ON contrato.parametro (modo, configuracao);

DROP TRIGGER IF EXISTS trg_parametro_set_updated_on ON contrato.parametro;
CREATE TRIGGER trg_parametro_set_updated_on
BEFORE UPDATE ON contrato.parametro
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parametro_created_by_id') THEN
    ALTER TABLE contrato.parametro
      ADD CONSTRAINT fk_parametro_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parametro_updated_by_id') THEN
    ALTER TABLE contrato.parametro
      ADD CONSTRAINT fk_parametro_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.periodo_pagamento (equivalente ao legado SQL Server)
-- Origem: [contrato].[periodo_pagamento]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.periodo_pagamento (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(100) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_periodo_pagamento_descricao ON contrato.periodo_pagamento (descricao);

DROP TRIGGER IF EXISTS trg_periodo_pagamento_set_updated_on ON contrato.periodo_pagamento;
CREATE TRIGGER trg_periodo_pagamento_set_updated_on
BEFORE UPDATE ON contrato.periodo_pagamento
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_periodo_pagamento_created_by_id') THEN
    ALTER TABLE contrato.periodo_pagamento
      ADD CONSTRAINT fk_periodo_pagamento_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_periodo_pagamento_updated_by_id') THEN
    ALTER TABLE contrato.periodo_pagamento
      ADD CONSTRAINT fk_periodo_pagamento_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.rescisao (equivalente ao legado SQL Server)
-- Origem: [contrato].[rescisao]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.rescisao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  ano smallint NOT NULL,
  numero varchar(20) NULL,
  motivo varchar(50) NULL,
  dt_termo date NOT NULL,
  dt_rescisao date NOT NULL,
  dt_publicacao date NULL,
  vl_multa numeric(29,6) NULL DEFAULT 0,
  vl_indenizacao numeric(29,6) NULL DEFAULT 0,
  exame_previo boolean NULL DEFAULT false,
  artigo varchar(50) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_rescisao_ano_numero ON contrato.rescisao (ano, numero);
CREATE INDEX IF NOT EXISTS idx_rescisao_dt_rescisao ON contrato.rescisao (dt_rescisao);

DROP TRIGGER IF EXISTS trg_rescisao_set_updated_on ON contrato.rescisao;
CREATE TRIGGER trg_rescisao_set_updated_on
BEFORE UPDATE ON contrato.rescisao
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rescisao_created_by_id') THEN
    ALTER TABLE contrato.rescisao
      ADD CONSTRAINT fk_rescisao_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rescisao_updated_by_id') THEN
    ALTER TABLE contrato.rescisao
      ADD CONSTRAINT fk_rescisao_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_aditivo (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_aditivo]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_aditivo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(30) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_tipo_aditivo_descricao ON contrato.tipo_aditivo (descricao);

DROP TRIGGER IF EXISTS trg_tipo_aditivo_set_updated_on ON contrato.tipo_aditivo;
CREATE TRIGGER trg_tipo_aditivo_set_updated_on
BEFORE UPDATE ON contrato.tipo_aditivo
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_aditivo_created_by_id') THEN
    ALTER TABLE contrato.tipo_aditivo
      ADD CONSTRAINT fk_tipo_aditivo_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_aditivo_updated_by_id') THEN
    ALTER TABLE contrato.tipo_aditivo
      ADD CONSTRAINT fk_tipo_aditivo_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_certidao (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_certidao]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_certidao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(30) NOT NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL,
  CONSTRAINT uq_tipo_certidao_descricao UNIQUE (descricao)
);

DROP TRIGGER IF EXISTS trg_tipo_certidao_set_updated_on ON contrato.tipo_certidao;
CREATE TRIGGER trg_tipo_certidao_set_updated_on
BEFORE UPDATE ON contrato.tipo_certidao
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_certidao_created_by_id') THEN
    ALTER TABLE contrato.tipo_certidao
      ADD CONSTRAINT fk_tipo_certidao_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_certidao_updated_by_id') THEN
    ALTER TABLE contrato.tipo_certidao
      ADD CONSTRAINT fk_tipo_certidao_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_contrato (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_contrato]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_contrato (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(50) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL,
  tp varchar(32) NULL,
  CONSTRAINT uq_tipo_contrato_descricao UNIQUE (descricao)
);

CREATE INDEX IF NOT EXISTS idx_tipo_contrato_tp ON contrato.tipo_contrato (tp);

DROP TRIGGER IF EXISTS trg_tipo_contrato_set_updated_on ON contrato.tipo_contrato;
CREATE TRIGGER trg_tipo_contrato_set_updated_on
BEFORE UPDATE ON contrato.tipo_contrato
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_contrato_created_by_id') THEN
    ALTER TABLE contrato.tipo_contrato
      ADD CONSTRAINT fk_tipo_contrato_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_contrato_updated_by_id') THEN
    ALTER TABLE contrato.tipo_contrato
      ADD CONSTRAINT fk_tipo_contrato_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_convenio (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_convenio]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_convenio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(30) NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_tipo_convenio_descricao ON contrato.tipo_convenio (descricao);

DROP TRIGGER IF EXISTS trg_tipo_convenio_set_updated_on ON contrato.tipo_convenio;
CREATE TRIGGER trg_tipo_convenio_set_updated_on
BEFORE UPDATE ON contrato.tipo_convenio
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_convenio_created_by_id') THEN
    ALTER TABLE contrato.tipo_convenio
      ADD CONSTRAINT fk_tipo_convenio_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_convenio_updated_by_id') THEN
    ALTER TABLE contrato.tipo_convenio
      ADD CONSTRAINT fk_tipo_convenio_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_obra (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_obra]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_obra (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  created_on timestamp without time zone NULL,
  descricao varchar(50) NOT NULL,
  created_by_id bigint NULL,
  updated_by_id bigint NULL,
  CONSTRAINT uq_tipo_obra_descricao UNIQUE (descricao)
);

DROP TRIGGER IF EXISTS trg_tipo_obra_set_updated_on ON contrato.tipo_obra;
CREATE TRIGGER trg_tipo_obra_set_updated_on
BEFORE UPDATE ON contrato.tipo_obra
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_obra_created_by_id') THEN
    ALTER TABLE contrato.tipo_obra
      ADD CONSTRAINT fk_tipo_obra_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_obra_updated_by_id') THEN
    ALTER TABLE contrato.tipo_obra
      ADD CONSTRAINT fk_tipo_obra_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.tipo_veiculo (equivalente ao legado SQL Server)
-- Origem: [contrato].[tipo_veiculo]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.tipo_veiculo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar(10) NULL,
  created_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  updated_on timestamp without time zone NULL
);

CREATE INDEX IF NOT EXISTS idx_tipo_veiculo_descricao ON contrato.tipo_veiculo (descricao);

DROP TRIGGER IF EXISTS trg_tipo_veiculo_set_updated_on ON contrato.tipo_veiculo;
CREATE TRIGGER trg_tipo_veiculo_set_updated_on
BEFORE UPDATE ON contrato.tipo_veiculo
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_veiculo_created_by_id') THEN
    ALTER TABLE contrato.tipo_veiculo
      ADD CONSTRAINT fk_tipo_veiculo_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tipo_veiculo_updated_by_id') THEN
    ALTER TABLE contrato.tipo_veiculo
      ADD CONSTRAINT fk_tipo_veiculo_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END
$$;

COMMIT;

-- ==========================================================
-- Tabela: contrato.transportador (equivalente ao legado SQL Server)
-- Origem: [contrato].[transportador]
-- ==========================================================

BEGIN;

CREATE TABLE IF NOT EXISTS contrato.transportador (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_on timestamp without time zone NULL,
  updated_by_id bigint NULL,
  created_on timestamp without time zone NULL,
  created_by_id bigint NULL,
  contrato_id bigint NULL,
  transportador_id bigint NULL,
  placa varchar(10) NULL,
  motorista varchar(50) NULL,
  cpf varchar(11) NULL,
  observacao text NULL,
  vl numeric(29,6) NULL DEFAULT 0,
  frete varchar(32) NULL,
  qt numeric(28,10) NULL DEFAULT 0,
  dt_embarque date NULL,
  dt_entrega date NULL,
  km decimal(28,8) NULL DEFAULT 0,
  qt_chegada decimal(28,8) NULL DEFAULT 0,
  equipamento_id bigint NULL
);

CREATE INDEX IF NOT EXISTS idx_transportador_contrato_id ON contrato.transportador (contrato_id);
CREATE INDEX IF NOT EXISTS idx_transportador_transportador_id ON contrato.transportador (transportador_id);
CREATE INDEX IF NOT EXISTS idx_transportador_equipamento_id ON contrato.transportador (equipamento_id);

DROP TRIGGER IF EXISTS trg_transportador_set_updated_on ON contrato.transportador;
CREATE TRIGGER trg_transportador_set_updated_on
BEFORE UPDATE ON contrato.transportador
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

DO $$
BEGIN
  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transportador_contrato_id') THEN
    ALTER TABLE contrato.transportador
      ADD CONSTRAINT fk_transportador_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transportador_created_by_id') THEN
    ALTER TABLE contrato.transportador
      ADD CONSTRAINT fk_transportador_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transportador_transportador_id') THEN
    ALTER TABLE contrato.transportador
      ADD CONSTRAINT fk_transportador_transportador_id
      FOREIGN KEY (transportador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transportador_updated_by_id') THEN
    ALTER TABLE contrato.transportador
      ADD CONSTRAINT fk_transportador_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('frota.equipamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transportador_equipamento_id') THEN
    ALTER TABLE contrato.transportador
      ADD CONSTRAINT fk_transportador_equipamento_id
      FOREIGN KEY (equipamento_id) REFERENCES frota.equipamento(id);
  END IF;
END
$$;

COMMIT;
