BEGIN;

CREATE SCHEMA IF NOT EXISTS contrato;

-- =====================================================================
-- Função padrão de updated_on (usada pelos triggers abaixo)
-- =====================================================================
CREATE OR REPLACE FUNCTION contrato.set_updated_on()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_on = now();
  RETURN NEW;
END;
$$;

-- =====================================================================
-- Tabela: contrato.clausula (catálogo de cláusulas)
-- =====================================================================
CREATE TABLE IF NOT EXISTS contrato.clausula (
  id BIGSERIAL PRIMARY KEY,
  descricao VARCHAR(100) NOT NULL UNIQUE,
  created_by_id BIGINT NULL,
  created_on TIMESTAMP NULL,
  updated_by_id BIGINT NULL,
  updated_on TIMESTAMP NULL,
  codigo VARCHAR(100) NULL,
  _descricao VARCHAR(1024) NULL
);

CREATE INDEX IF NOT EXISTS idx_contrato_clausula_codigo
  ON contrato.clausula (codigo);

-- =====================================================================
-- Tabela: contrato.contrato (legado)
-- =====================================================================
CREATE TABLE IF NOT EXISTS contrato.contrato (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on timestamp without time zone NULL,
  updated_on timestamp without time zone NULL,
  ano smallint NOT NULL,
  numero varchar(20) NULL,
  descricao varchar(80) NULL,
  licitacao varchar(20) NULL,
  dispensa varchar(20) NULL,
  dt_assinatura date NULL,
  dt_publicacao date NULL,
  dt_inicio date NULL,
  dt_vencimento date NULL,
  responsavel_juridico varchar(100) NULL,
  vl_mao_obra numeric(29,6) NULL DEFAULT 0,
  vl numeric(29,6) NOT NULL DEFAULT 0,
  objeto text NULL,
  execucao text NULL,
  status varchar(32) NULL,
  testemunha varchar(100) NULL,
  testemunha2 varchar(100) NULL,
  cpf_testemunha varchar(14) NULL,
  cpf_testemunha2 varchar(14) NULL,
  contrato_anterior_id bigint NULL,
  created_by_id bigint NULL,
  empresa_id bigint NULL,
  fornecedor_id bigint NULL,
  tipo_contrato_id bigint NULL,
  updated_by_id bigint NULL,
  vl_unitario numeric(29,6) NULL DEFAULT 0,
  qt numeric(29,6) NULL DEFAULT 0,
  vl_total numeric(29,6) NULL DEFAULT 0,
  tp_contrato varchar(32) NULL,
  prazo_entrega date NULL,
  observacao text NULL,
  vl_comissao numeric(29,6) NULL DEFAULT 0,
  deposito_id bigint NULL,
  insumo_id bigint NULL,
  fazenda_id bigint NULL,
  fazenda_origem varchar(200) NULL,
  comissionado_id bigint NULL,
  tabela_preco_id bigint NULL,
  fazenda_destino_id bigint NULL,
  tp_entrada varchar(32) NULL,
  frete_confinamento varchar(32) NULL,
  sexo varchar(32) NULL,
  emissor_nota varchar(32) NULL,
  jejum varchar(32) NULL,
  qt_animal int NULL,
  qt_animal_mapa int NULL,
  vl_cepea numeric(29,6) NULL DEFAULT 0,
  vl_arroba numeric(29,6) NULL DEFAULT 0,
  vl_cabeca numeric(29,6) NULL DEFAULT 0,
  peso_bruto_total numeric(29,6) NULL DEFAULT 0,
  peso_bruto_cabeca numeric(29,6) NULL DEFAULT 0,
  peso_rc numeric(29,6) NULL DEFAULT 0,
  peso_medio_arroba numeric(29,6) NULL DEFAULT 0,
  previsao_chegada date NULL,
  vl_total_compra numeric(29,6) NULL DEFAULT 0,
  peso_medio_abate numeric(29,6) NULL DEFAULT 0,
  gmd_projetado numeric(29,6) NULL DEFAULT 0,
  gmc_projetado numeric(29,6) NULL DEFAULT 0,
  consumo_pv numeric(29,6) NULL DEFAULT 0,
  custo_ton_ms numeric(29,6) NULL DEFAULT 0,
  custo_ton_ms_vendido numeric(29,6) NULL DEFAULT 0,
  custo_operacional numeric(29,6) NULL DEFAULT 0,
  custo_operacional_vendido numeric(29,6) NULL DEFAULT 0,
  vl_frete_cab numeric(29,6) NULL DEFAULT 0,
  vl_icms numeric(29,6) NULL DEFAULT 0,
  vl_icms_frete numeric(29,6) NULL DEFAULT 0,
  vl_protocolo numeric(29,6) NULL DEFAULT 0,
  vl_brinco numeric(29,6) NULL DEFAULT 0,
  vl_gta_cab numeric(29,6) NULL DEFAULT 0,
  dias_minimos int NULL,
  dls date NULL,
  hr_pesagem time NULL,
  vl_frete_arroba numeric(29,6) NULL DEFAULT 0,
  vendedor_id bigint NULL,
  comprador_id bigint NULL,
  faturador_id bigint NULL,
  frigorifico_id bigint NULL,
  rc_fixo numeric(29,6) NULL DEFAULT 0,
  dt_embarque date NULL,
  dt_pesagem date NULL,
  dt_abate date NULL,
  dt_recebimento date NULL,
  observacao_financeiro text NULL,
  tp_saida varchar(32) NULL,
  originador_id bigint NULL,
  tabela_boitel_id bigint NULL,
  periodo_producao_id bigint NULL,
  permuta boolean NULL DEFAULT false,
  contrato_permuta_id bigint NULL,
  contrato_cedente_id bigint NULL,
  aditivo boolean NULL DEFAULT false,
  tp_aditivo_id bigint NULL,
  parceiro_id bigint NULL,
  dt_fim date NULL,
  responsavel_juridico_id bigint NULL,
  tp_contrato_id bigint NULL,
  pedido_id bigint NULL,
  peso_referencia varchar(32) NULL,
  qt_animal_gta int NULL,
  qt_animal_desembarcado int NULL,
  qt_animal_morto int NULL,
  qt_animal_lesionado int NULL,
  peso_total_quebra numeric(29,6) NULL DEFAULT 0,
  tp varchar(4000) NULL,
  rc_entrada numeric(29,6) NULL DEFAULT 0,
  peso_medio_mapa numeric(29,6) NULL DEFAULT 0,
  peso_medio_chegada decimal(28,8) NOT NULL DEFAULT 0,
  dt_pesagem_origem date NULL,
  dt_previsao_chegada date NULL,
  rc_saida numeric(29,6) NULL DEFAULT 0,
  vl_arroba_saida numeric(29,6) NULL DEFAULT 0,
  calculo_frete varchar(4000) NULL,
  frete varchar(4000) NULL,
  vl_unit_frete numeric(29,6) NULL DEFAULT 0,
  vl_arroba_produzida numeric(29,6) NULL DEFAULT 0,
  desconto_acerto boolean NULL DEFAULT false,
  valor_venda_futura boolean NULL,
  faturador_entrada_id bigint NULL,
  descricao_desconto varchar(4000) NULL,
  tx_juros_parceiro numeric(29,6) NULL DEFAULT 0,
  qt_animal_previsto decimal(29,6) NULL DEFAULT 0,
  qt_animal_selecionado decimal(29,6) NULL DEFAULT 0,
  current_approval_level_id bigint NULL,
  rota_id bigint NULL,
  old__distancia numeric(29,6) NULL DEFAULT 0,
  comissao_id bigint NULL,
  old__distancia_1 int NULL,
  distancia decimal(29,6) NULL DEFAULT 0,
  condicao_pagamento_id bigint NULL,
  ref_model varchar(128) NULL,
  ref_object_id bigint NULL,
  categoria_id bigint NULL,
  venda_futura boolean NULL DEFAULT false,
  cidade_id bigint NULL,
  estado_id bigint NULL,
  contato varchar(200) NULL,
  clausula_id bigint NULL,
  titulo_clausula varchar(100) NULL,
  assinatura_empresa varchar(100) NULL,
  assinatura_parceiro varchar(100) NULL,
  forma_pagamento_id bigint NULL,
  qt_animal_chegada int NULL,
  responsavel_quebra varchar(32) NULL,
  peso_medio_identificacao numeric(28,10) NULL DEFAULT 0,
  qt_animal_processamento numeric(28,10) NULL DEFAULT 0,
  programacao_retirada text NULL,
  programacao_pagamento text NULL,
  vl_arroba_dif numeric(28,10) NULL DEFAULT 0,
  vl_oferta decimal(28,8) NULL DEFAULT 0,
  vl_contra_oferta decimal(28,8) NULL DEFAULT 0,
  vl_tabela decimal(28,8) NULL DEFAULT 0,
  quebra_peso_kg decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_arr decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_pct decimal(28,8) NOT NULL DEFAULT 0,
  quebra_peso_curral_kg decimal(28,8) NULL DEFAULT 0,
  quebra_peso_curral_arr decimal(28,8) NULL DEFAULT 0,
  quebra_peso_curral_pct decimal(28,8) NULL DEFAULT 0,
  qt_animal_trava int NULL,
  vl_arroba_trava decimal(28,8) NULL DEFAULT 0,
  contrato_principal_id bigint NULL,
  contraoferta varchar(1) NULL,
  calculo_adiantamento varchar(32) NULL,
  vl_desconto_adiantamento decimal(28,8) NULL DEFAULT 0,
  fazenda_origem_fk_id bigint NULL,
  pct_parceria decimal(28,6) NULL DEFAULT 0,
  pct_recria decimal(28,6) NULL DEFAULT 0,
  vl_desconto_venda decimal(28,6) NULL DEFAULT 0,
  referencia_diaria varchar(32) NULL,
  vl_diaria decimal(28,6) NULL,
  peso_considerado decimal(28,6) NULL,
  raca_id bigint NULL,
  tabela_produzida_id bigint NULL,
  _vl_comissao numeric(28,10) NULL,
  b1_codigo_pedido varchar(128) NULL,
  b1_codigo varchar(128) NULL,
  b1_created_by varchar(128) NULL,
  b1_approved_by varchar(128) NULL,
  b1_object_name varchar(128) NULL,
  b1_vl_pago decimal(28,6) NULL
);

CREATE INDEX IF NOT EXISTS idx_contrato_contrato_tp ON contrato.contrato (tp_contrato);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_ano_numero ON contrato.contrato (ano, numero);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_parceiro ON contrato.contrato (parceiro_id);
CREATE INDEX IF NOT EXISTS idx_contrato_contrato_empresa ON contrato.contrato (empresa_id);

DROP TRIGGER IF EXISTS trg_contrato_set_updated_on ON contrato.contrato;
CREATE TRIGGER trg_contrato_set_updated_on
BEFORE UPDATE ON contrato.contrato
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

-- =====================================================================
-- Tabela: contrato.clausula_contrato (liga cláusula ao contrato)
-- =====================================================================
CREATE TABLE IF NOT EXISTS contrato.clausula_contrato (
  id BIGSERIAL PRIMARY KEY,
  contrato_id BIGINT NULL,
  codigo VARCHAR(50) NULL,
  referencia VARCHAR(100) NULL,
  descricao TEXT NULL,
  created_by_id BIGINT NULL,
  created_on TIMESTAMP NULL,
  updated_by_id BIGINT NULL,
  updated_on TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS idx_clausula_contrato_contrato_id
  ON contrato.clausula_contrato (contrato_id);

DROP TRIGGER IF EXISTS trg_clausula_contrato_set_updated_on ON contrato.clausula_contrato;
CREATE TRIGGER trg_clausula_contrato_set_updated_on
BEFORE UPDATE ON contrato.clausula_contrato
FOR EACH ROW
EXECUTE FUNCTION contrato.set_updated_on();

-- =====================================================================
-- FKs condicionais (só cria se tabela de referência existir)
-- =====================================================================
DO $$
BEGIN
  IF to_regclass('contrato.clausula') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_clausula_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_clausula_id
      FOREIGN KEY (clausula_id) REFERENCES contrato.clausula(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_origem_fk_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_origem_fk_id
      FOREIGN KEY (fazenda_origem_fk_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('produto.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_forma_pagamento_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_forma_pagamento_id
      FOREIGN KEY (forma_pagamento_id) REFERENCES produto.condicao_pagamento(id);
  END IF;

  IF to_regclass('confinamento.raca') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_raca_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_raca_id
      FOREIGN KEY (raca_id) REFERENCES confinamento.raca(id);
  END IF;

  IF to_regclass('confinamento.tabela_produzida') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_produzida_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_produzida_id
      FOREIGN KEY (tabela_produzida_id) REFERENCES confinamento.tabela_produzida(id);
  END IF;

  IF to_regclass('confinamento.categoria') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_categoria_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_categoria_id
      FOREIGN KEY (categoria_id) REFERENCES confinamento.categoria(id);
  END IF;

  IF to_regclass('dbo.res_city') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_cidade_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_cidade_id
      FOREIGN KEY (cidade_id) REFERENCES dbo.res_city(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comissao_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comissao_id
      FOREIGN KEY (comissao_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comissionado_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comissionado_id
      FOREIGN KEY (comissionado_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_comprador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_comprador_id
      FOREIGN KEY (comprador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('confinamento.condicao_pagamento') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_condicao_pagamento_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_condicao_pagamento_id
      FOREIGN KEY (condicao_pagamento_id) REFERENCES confinamento.condicao_pagamento(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_anterior_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_anterior_id
      FOREIGN KEY (contrato_anterior_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_cedente_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_cedente_id
      FOREIGN KEY (contrato_cedente_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_contrato_permuta_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_contrato_permuta_id
      FOREIGN KEY (contrato_permuta_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_created_by_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.mail_approval_level') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_current_approval_level_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_current_approval_level_id
      FOREIGN KEY (current_approval_level_id) REFERENCES dbo.mail_approval_level(id);
  END IF;

  IF to_regclass('estoque.deposito') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_deposito_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_deposito_id
      FOREIGN KEY (deposito_id) REFERENCES estoque.deposito(id);
  END IF;

  IF to_regclass('dbo.res_company') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_empresa_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_empresa_id
      FOREIGN KEY (empresa_id) REFERENCES dbo.res_company(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_country_state') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_estado_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_estado_id
      FOREIGN KEY (estado_id) REFERENCES dbo.res_country_state(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_faturador_entrada_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_faturador_entrada_id
      FOREIGN KEY (faturador_entrada_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_faturador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_faturador_id
      FOREIGN KEY (faturador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_destino_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_destino_id
      FOREIGN KEY (fazenda_destino_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fazenda_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fazenda_id
      FOREIGN KEY (fazenda_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_fornecedor_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_fornecedor_id
      FOREIGN KEY (fornecedor_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_frigorifico_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_frigorifico_id
      FOREIGN KEY (frigorifico_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('produto.item') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_insumo_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_insumo_id
      FOREIGN KEY (insumo_id) REFERENCES produto.item(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_originador_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_originador_id
      FOREIGN KEY (originador_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_parceiro_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_parceiro_id
      FOREIGN KEY (parceiro_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('produto.pedido') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_pedido_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_pedido_id
      FOREIGN KEY (pedido_id) REFERENCES produto.pedido(id);
  END IF;

  IF to_regclass('agricola.periodo_producao') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_periodo_producao_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_periodo_producao_id
      FOREIGN KEY (periodo_producao_id) REFERENCES agricola.periodo_producao(id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_responsavel_juridico_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_responsavel_juridico_id
      FOREIGN KEY (responsavel_juridico_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('agro.fazenda') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_rota_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_rota_id
      FOREIGN KEY (rota_id) REFERENCES agro.fazenda(id);
  END IF;

  IF to_regclass('confinamento.tabela_boitel') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_boitel_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_boitel_id
      FOREIGN KEY (tabela_boitel_id) REFERENCES confinamento.tabela_boitel(id);
  END IF;

  IF to_regclass('confinamento.tabela_preco') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tabela_preco_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tabela_preco_id
      FOREIGN KEY (tabela_preco_id) REFERENCES confinamento.tabela_preco(id);
  END IF;

  IF to_regclass('contrato.tipo_contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tipo_contrato_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tipo_contrato_id
      FOREIGN KEY (tipo_contrato_id) REFERENCES contrato.tipo_contrato(id);
  END IF;

  IF to_regclass('contrato.tipo_aditivo') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tp_aditivo_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tp_aditivo_id
      FOREIGN KEY (tp_aditivo_id) REFERENCES contrato.tipo_aditivo(id);
  END IF;

  IF to_regclass('contrato.tipo_contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_tp_contrato_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_tp_contrato_id
      FOREIGN KEY (tp_contrato_id) REFERENCES contrato.tipo_contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_updated_by_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.res_partner') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_contrato_vendedor_id') THEN
    ALTER TABLE contrato.contrato
      ADD CONSTRAINT fk_contrato_vendedor_id
      FOREIGN KEY (vendedor_id) REFERENCES dbo.res_partner(id);
  END IF;

  IF to_regclass('contrato.contrato') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_contrato_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_contrato_id
      FOREIGN KEY (contrato_id) REFERENCES contrato.contrato(id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_created_by_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_created_by_id
      FOREIGN KEY (created_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;

  IF to_regclass('dbo.auth_user') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clausula_contrato_updated_by_id') THEN
    ALTER TABLE contrato.clausula_contrato
      ADD CONSTRAINT fk_clausula_contrato_updated_by_id
      FOREIGN KEY (updated_by_id) REFERENCES dbo.auth_user(partner_ptr_id);
  END IF;
END $$;

COMMIT;
