services:
  captarsuite:
    container_name: captarsuite-web
    image: captarsuite:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "${APP_PORT:-3000}:3000"
